export const additionalBusinesses = [
  // More Restaurants
  {
    name: "Pho To Chau",
    slug: "pho-to-chau-honolulu",
    category: "Restaurant",
    subcategory: "Vietnamese Restaurant",
    description: "Family-owned Vietnamese restaurant serving authentic pho and traditional dishes. Known for their rich broth and fresh ingredients.",
    address: "1007 Dillingham Blvd Ste 101",
    city: "Honolulu",
    island: "Oahu",
    phone: "(808) 842-8443",
    rating: 4.3,
    reviewCount: 87,
    priceRange: "$$",
    features: ["Dine-in", "Takeout", "Vietnamese Speaking Staff", "Parking"],
    lat: 21.3294,
    lng: -157.8754,
  },
  {
    name: "Viet Huong Restaurant",
    slug: "viet-huong-restaurant",
    category: "Restaurant",
    subcategory: "Vietnamese Restaurant",
    description: "Traditional Vietnamese cuisine with a focus on vermicelli bowls, spring rolls, and authentic flavors from central Vietnam.",
    address: "1140 12th Ave",
    city: "Honolulu",
    island: "Oahu",
    phone: "(808) 735-7581",
    rating: 4.5,
    reviewCount: 112,
    priceRange: "$$",
    features: ["Dine-in", "Takeout", "Family Friendly", "Vietnamese Speaking Staff"],
    lat: 21.2784,
    lng: -157.8057,
  },
  {
    name: "Hale Vietnam",
    slug: "hale-vietnam-honolulu",
    category: "Restaurant",
    subcategory: "Vietnamese Restaurant",
    description: "Modern Vietnamese restaurant offering creative takes on traditional dishes with a contemporary atmosphere.",
    address: "1140 12th Ave",
    city: "Honolulu",
    island: "Oahu",
    phone: "(808) 735-7581",
    rating: 4.6,
    reviewCount: 203,
    priceRange: "$$$",
    features: ["Dine-in", "Takeout", "Delivery", "Reservations", "WiFi", "Credit Cards"],
    lat: 21.2784,
    lng: -157.8057,
  },

  // Coffee Shops & Cafes
  {
    name: "Hoku Vietnamese Bistro & Cafe",
    slug: "hoku-vietnamese-bistro",
    category: "Cafe",
    subcategory: "Coffee Shop",
    description: "Cozy cafe serving Vietnamese coffee, banh mi sandwiches, and light bites. Perfect spot for a quick lunch or coffee break.",
    address: "1613 Nu'uanu Ave",
    city: "Honolulu",
    island: "Oahu",
    phone: "(808) 531-6268",
    rating: 4.4,
    reviewCount: 156,
    priceRange: "$$",
    features: ["Dine-in", "Takeout", "WiFi", "Vietnamese Coffee", "Outdoor Seating"],
    lat: 21.3156,
    lng: -157.8617,
  },
  {
    name: "Cafe Duc Loi",
    slug: "cafe-duc-loi-honolulu",
    category: "Cafe",
    subcategory: "Vietnamese Cafe",
    description: "Traditional Vietnamese cafe serving strong coffee, sweet condensed milk drinks, and fresh pastries.",
    address: "1145 N King St",
    city: "Honolulu",
    island: "Oahu",
    phone: "(808) 841-8855",
    rating: 4.2,
    reviewCount: 78,
    priceRange: "$",
    features: ["Takeout", "Cash Only", "Vietnamese Coffee", "Parking"],
    lat: 21.3173,
    lng: -157.8574,
  },

  // Grocery & Markets
  {
    name: "Viet Hoa Market",
    slug: "viet-hoa-market-honolulu",
    category: "Grocery",
    subcategory: "Asian Supermarket",
    description: "Large Vietnamese and Asian grocery store with fresh produce, imported goods, and a deli section.",
    address: "1104 Maunakea St",
    city: "Honolulu",
    island: "Oahu",
    phone: "(808) 533-6863",
    rating: 4.1,
    reviewCount: 92,
    priceRange: "$$",
    features: ["Parking", "Vietnamese Speaking Staff", "Fresh Produce", "Deli"],
    lat: 21.3116,
    lng: -157.8631,
  },
  {
    name: "Duc's Bistro",
    slug: "ducs-bistro-honolulu",
    category: "Restaurant",
    subcategory: "Vietnamese Restaurant",
    description: "Upscale Vietnamese dining experience with a modern twist on classic dishes. Known for their presentation and quality.",
    address: "1188 Maunakea St",
    city: "Honolulu",
    island: "Oahu",
    phone: "(808) 531-6325",
    rating: 4.7,
    reviewCount: 284,
    priceRange: "$$$",
    features: ["Dine-in", "Reservations", "Wine List", "Vegan Options", "Credit Cards"],
    lat: 21.3132,
    lng: -157.8632,
  },

  // Beauty & Wellness
  {
    name: "Saigon Nails & Spa",
    slug: "saigon-nails-spa-honolulu",
    category: "Beauty & Wellness",
    subcategory: "Nail Salon",
    description: "Professional nail salon offering manicures, pedicures, and spa services with experienced Vietnamese technicians.",
    address: "909 Kapahulu Ave",
    city: "Honolulu",
    island: "Oahu",
    phone: "(808) 735-6245",
    rating: 4.5,
    reviewCount: 167,
    priceRange: "$$",
    features: ["Appointments", "Walk-ins", "Credit Cards", "WiFi"],
    lat: 21.2729,
    lng: -157.8160,
  },
  {
    name: "Diamond Nails",
    slug: "diamond-nails-honolulu",
    category: "Beauty & Wellness",
    subcategory: "Nail Salon",
    description: "Elegant nail salon providing high-quality nail care, gel polish, and nail art services.",
    address: "1750 Kalakaua Ave",
    city: "Honolulu",
    island: "Oahu",
    phone: "(808) 941-2922",
    rating: 4.3,
    reviewCount: 198,
    priceRange: "$$",
    features: ["Appointments", "Credit Cards", "Wheelchair Accessible"],
    lat: 21.2793,
    lng: -157.8292,
  },

  // Professional Services
  {
    name: "Nguyen Law Office",
    slug: "nguyen-law-office-honolulu",
    category: "Professional Services",
    subcategory: "Legal Services",
    description: "Full-service law firm specializing in immigration, family law, and business matters. Bilingual Vietnamese services available.",
    address: "1132 Bishop St Ste 1910",
    city: "Honolulu",
    island: "Oahu",
    phone: "(808) 524-5500",
    rating: 4.8,
    reviewCount: 45,
    priceRange: "$$$",
    features: ["Appointments", "Vietnamese Speaking Staff", "Free Consultation", "Parking"],
    lat: 21.3099,
    lng: -157.8612,
  },
  {
    name: "Pham & Associates CPA",
    slug: "pham-associates-cpa",
    category: "Professional Services",
    subcategory: "Accounting & Tax",
    description: "Certified public accountants providing tax preparation, bookkeeping, and financial consulting services.",
    address: "99-128 Aiea Heights Dr Ste 102",
    city: "Aiea",
    island: "Oahu",
    phone: "(808) 488-7777",
    rating: 4.9,
    reviewCount: 67,
    priceRange: "$$",
    features: ["Appointments", "Vietnamese Speaking Staff", "Free Consultation"],
    lat: 21.3879,
    lng: -157.9307,
  },

  // Big Island
  {
    name: "Pho Big Island",
    slug: "pho-big-island-kona",
    category: "Restaurant",
    subcategory: "Vietnamese Restaurant",
    description: "Only authentic Vietnamese restaurant on the Big Island, serving pho, banh mi, and traditional dishes.",
    address: "75-5744 Alii Dr",
    city: "Kailua-Kona",
    island: "Big Island",
    phone: "(808) 329-7866",
    rating: 4.4,
    reviewCount: 234,
    priceRange: "$$",
    features: ["Dine-in", "Takeout", "Parking", "Ocean View"],
    lat: 19.6391,
    lng: -155.9969,
  },

  // Maui
  {
    name: "Pho Saigon 808",
    slug: "pho-saigon-808-maui",
    category: "Restaurant",
    subcategory: "Vietnamese Restaurant",
    description: "Family-run Vietnamese restaurant in Kahului bringing authentic flavors to Maui.",
    address: "275 W Ka'ahumanu Ave",
    city: "Kahului",
    island: "Maui",
    phone: "(808) 877-6813",
    rating: 4.3,
    reviewCount: 145,
    priceRange: "$$",
    features: ["Dine-in", "Takeout", "Vietnamese Speaking Staff", "Family Friendly"],
    lat: 20.8897,
    lng: -156.4729,
  },
  {
    name: "Vietnamese Cuisine Maui",
    slug: "vietnamese-cuisine-maui",
    category: "Restaurant",
    subcategory: "Vietnamese Restaurant",
    description: "Authentic Vietnamese food with a focus on fresh local ingredients and traditional cooking methods.",
    address: "1280 S Kihei Rd",
    city: "Kihei",
    island: "Maui",
    phone: "(808) 879-9833",
    rating: 4.5,
    reviewCount: 187,
    priceRange: "$$",
    features: ["Dine-in", "Takeout", "Vegan Options", "Parking"],
    lat: 20.7510,
    lng: -156.4523,
  },

  // More diverse businesses
  {
    name: "Little Saigon Bakery",
    slug: "little-saigon-bakery-honolulu",
    category: "Cafe",
    subcategory: "Vietnamese Bakery",
    description: "Traditional Vietnamese bakery offering fresh baguettes, banh mi, pastries, and cakes daily.",
    address: "1116 Smith St",
    city: "Honolulu",
    island: "Oahu",
    phone: "(808) 528-3663",
    rating: 4.6,
    reviewCount: 134,
    priceRange: "$",
    features: ["Takeout", "Cash Only", "Fresh Daily", "Parking"],
    lat: 21.3122,
    lng: -157.8620,
  },
];
